version: "3"

volumes:
    PDSC_DEVELOPMENT_DB_VOLUME:
        driver: local

networks:
    pdscnet:

services:
    web:
        image: pdsc/website
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    memory: 256M
        ports:
            - "80:80"
        networks:
            - pdscnet

    api-service:
        image: pdsc/api-service-production
        hostname: api-service
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
            DEBUG: "pdsc:*"
            PDSC_DB_HOST: "api_db"
            PDSC_DB_PORT: "5432"
            PDSC_DB_USER: "paradisec"
            PDSC_DB_PASSWORD: "$POSTGRES_PASSWORD"
            PDSC_DB_DATABASE: "paradisec"
            PDSC_HARVEST_DOWNLOAD: "/srv/data/scrape"
            PDSC_HARVEST_REPOSITORY: "/srv/data/repository"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    memory: 512M
        volumes:
            - /srv/data/olac-datasource:/srv/data
        command: ["pm2-runtime", "start", "ecosystem.config.js"]
        networks:
            - pdscnet

    api_db:
        image: postgres:10-alpine
        hostname: api_db
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
            POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
            POSTGRES_USER: "paradisec"
            POSTGRES_DB: "paradisec"
            PGDATA: /postgresql/data
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    memory: 512M
        volumes:
            - PDSC_DEVELOPMENT_DB_VOLUME:/postgresql
        networks:
            - pdscnet
